package com.hipla.channel.entity

class FloorDetails(val id: Int, val name: String)

fun generateFloors(): List<FloorDetails> {
    return mutableListOf<FloorDetails>().apply {
        //add(FloorDetails(0, "Ground floor"))
        add(FloorDetails(1, "1st floor"))
        add(FloorDetails(2, "2nd floor"))
        add(FloorDetails(3, "3rd floor"))
        add(FloorDetails(4, "4th floor"))
        add(FloorDetails(5, "5th floor"))
        add(FloorDetails(6, "6th floor"))
        add(FloorDetails(7, "7th floor"))
        add(FloorDetails(8, "8th floor"))
        add(FloorDetails(9, "9th floor"))
        add(FloorDetails(10, "10th floor"))
        add(FloorDetails(11, "11th floor"))
        add(FloorDetails(12, "12th floor"))
        add(FloorDetails(13, "13th floor"))
        add(FloorDetails(14, "14th floor"))
        add(FloorDetails(15, "15th floor"))
        add(FloorDetails(16, "16th floor"))
        add(FloorDetails(17, "17th floor"))
        add(FloorDetails(18, "18th floor"))
        add(FloorDetails(19, "19th floor"))
        add(FloorDetails(20, "20th floor"))
        add(FloorDetails(21, "21st floor"))
        add(FloorDetails(22, "22nd floor"))
        add(FloorDetails(23, "23rd floor"))
        add(FloorDetails(24, "24th floor"))
        add(FloorDetails(25, "25th floor"))
        add(FloorDetails(26, "26th floor"))
        add(FloorDetails(27, "27th floor"))
        add(FloorDetails(28, "28th floor"))
        add(FloorDetails(29, "29th floor"))
        add(FloorDetails(30, "30th floor"))
        add(FloorDetails(31, "31st floor"))
        add(FloorDetails(32, "32nd floor"))
        add(FloorDetails(33, "33rd floor"))
        add(FloorDetails(34, "34th floor"))
        add(FloorDetails(35, "35th floor"))
        add(FloorDetails(36, "36th floor"))
        add(FloorDetails(37, "37th floor"))
        add(FloorDetails(38, "38th floor"))
        add(FloorDetails(39, "39th floor"))
        add(FloorDetails(40, "40th floor"))
        add(FloorDetails(41, "41st floor"))
        add(FloorDetails(42, "42nd floor"))
        add(FloorDetails(43, "43rd floor"))
        add(FloorDetails(44, "44th floor"))
        add(FloorDetails(45, "45th floor"))
        add(FloorDetails(46, "46th floor"))
        add(FloorDetails(47, "47th floor"))
        add(FloorDetails(48, "48th floor"))
        add(FloorDetails(49, "49th floor"))
        add(FloorDetails(50, "50th floor"))
    }
}